# vim:ft=kitty

## name: {{name}}
## author: schemar
## license: MIT
## upstream: https://github.com/schemar/blueberry-peach/blob/main/ports/kitty/blueberry_peach_{{id}}.conf
## blurb: Handcrafted dark *and* light color scheme with a focus on legibility
## and consistency

#: The basic colors

foreground                      {{text}}
background                      {{background}}
selection_foreground            {{text}}
selection_background            {{surface1}}


#: Cursor colors

cursor                          {{violet}}
cursor_text_color               {{background}}
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       {{blue}}


#: kitty window border colors and terminal bell colors

active_border_color             {{violet}}
inactive_border_color           {{dimmed}}
bell_border_color               {{red}}
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           {{text}}
active_tab_background           {{surface1}}
inactive_tab_foreground         {{dimmed}}
inactive_tab_background         {{background}}
tab_bar_background              {{surface0}}
tab_bar_margin_color            {{dimmed}}


#: Colors for marks (marked text in the terminal)

mark1_foreground {{background}}
mark1_background {{teal}}
mark2_foreground {{background}}
mark2_background {{orange}}
mark3_foreground {{background}}
mark3_background {{pink}}


#: The basic 16 colors

#: black
color0 {{surface0}}
color8 {{surface1}}

#: red
color1 {{red}}
color9 {{red}}

#: green
color2  {{green}}
color10 {{green}}

#: yellow
color3  {{yellow}}
color11 {{yellow}}

#: blue
color4  {{blue}}
color12 {{blue}}

#: magenta
color5  {{violet}}
color13 {{pink}}

#: cyan
color6  {{teal}}
color14 {{teal}}

#: white
color7  {{subtext}}
color15 {{text}}


#: You can set the remaining 240 colors as color16 to color255.
