[colors]
ansi = [
  '{{surface1}}',
  '{{red}}',
  '{{green}}',
  '{{yellow}}',
  '{{blue}}',
  '{{violet}}',
  '{{teal}}',
  '{{subtext}}',
]
background = '{{background}}'
brights = [
  '{{dimmed}}',
  '{{red}}',
  '{{green}}',
  '{{yellow}}',
  '{{blue}}',
  '{{violet}}',
  '{{teal}}',
  '{{subtext}}',
]
compose_cursor = '{{pink}}'
cursor_bg = '{{violet}}'
cursor_border = '{{violet}}'
cursor_fg = '{{surface0}}'
foreground = '{{text}}'
scrollbar_thumb = '{{dimmed}}'
selection_bg = '{{surface1}}'
selection_fg = '{{text}}'
split = '{{overlay0}}'
visual_bell = '{{surface1}}'

[colors.indexed]
16 = '{{orange}}'
17 = '{{pink}}'

[colors.tab_bar]
background = '{{surface0}}'
inactive_tab_edge = '{{surface1}}'

[colors.tab_bar.active_tab]
bg_color = '{{violet}}'
fg_color = '{{surface0}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '{{surface0}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '{{background}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '{{surface1}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '{{surface1}}'
fg_color = '{{text}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = '{{name}}'
