ZHM_CURSOR_NORMAL="\e[0m\e[2 q\e]12;{{violet}}\a"
ZHM_CURSOR_INSERT="\e[0m\e[2 q\e]12;{{green}}\a"
ZHM_CURSOR_SELECT="\e[0m\e[2 q\e]12;{{blue}}\a"
ZHM_STYLE_CURSOR_SELECT="fg={{background}},bg={{blue}}"
ZHM_STYLE_CURSOR_INSERT="fg={{background}},bg={{green}}"
ZHM_STYLE_OTHER_CURSOR_NORMAL="fg={{background}},bg{{pink}}"
ZHM_STYLE_OTHER_CURSOR_SELECT="fg={{background}},bg={{teal}}"
ZHM_STYLE_OTHER_CURSOR_INSERT="fg={{background}},bg={{green}}"
ZHM_STYLE_SELECTION="fg={{text}},bg={{surface1}},bold"
