color={{background}}
bs-hl-color={{pink}}
caps-lock-bs-hl-color={{pink}}
caps-lock-key-hl-color={{green}}
inside-color={{background}}
inside-clear-color={{background}}
inside-caps-lock-color={{background}}
inside-ver-color={{background}}
inside-wrong-color={{background}}
key-hl-color={{green}}
layout-bg-color=#00000000
layout-border-color=#00000000
layout-text-color={{text}}
line-color=#00000000
line-clear-color=#00000000
line-caps-lock-color=#00000000
line-ver-color=#00000000
line-wrong-color=#00000000
ring-color={{surface1}}
ring-clear-color={{pink}}
ring-caps-lock-color={{orange}}
ring-ver-color={{blue}}
ring-wrong-color={{red}}
separator-color=#00000000
text-color={{text}}
text-clear-color={{pink}}
text-caps-lock-color={{orange}}
text-ver-color={{blue}}
text-wrong-color={{red}}
