# Syntax highlighting
# -------------------
"attribute" = "yellow"

"type" = "yellow"
"type.builtin" = "violet"
"type.enum.variant" = "teal"

"constructor" = "teal"

"constant" = "orange"
"constant.character" = "teal"
"constant.character.escape" = "pink"

"string" = "green"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"

"comment" = { fg = "teal", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "red", modifiers = ["italic"] }
"variable.builtin" = "red"
"variable.other.member" = "blue"

"label" = "teal" # used for lifetimes

"punctuation" = "overlay2"
"punctuation.special" = "teal"

"keyword" = "violet"
"keyword.control.conditional" = { fg = "violet", modifiers = ["italic"] }

"operator" = "teal"

"function" = "blue"
"function.macro" = "pink"

"tag" = "blue"

"namespace" = { fg = "yellow", modifiers = ["italic"] }

"special" = "blue" # fuzzy highlight

"markup.heading.1" = "red"
"markup.heading.2" = "orange"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "teal"
"markup.heading.6" = "blue"
"markup.list" = "teal"
"markup.list.unchecked" = "overlay2"
"markup.list.checked" = "green"
"markup.bold" = { fg = "red", modifiers = ["bold"] }
"markup.italic" = { fg = "red", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.link.text" = "blue"
"markup.link.label" = "teal"
"markup.raw" = "green"
"markup.quote" = "pink"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "background" }

"ui.linenr" = { fg = "dimmed" }
"ui.linenr.selected" = { fg = "blue" }

"ui.statusline" = { fg = "subtext", bg = "surface0" }
"ui.statusline.inactive" = { fg = "dimmed", bg = "surface0" }
"ui.statusline.normal" = { fg = "background", bg = "violet", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "background", bg = "green", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "background", bg = "blue", modifiers = [
  "bold",
] }

"ui.popup" = { fg = "text", bg = "surface0" }
"ui.window" = { fg = "surface0" }
"ui.help" = { fg = "text", bg = "surface0" }

"ui.bufferline" = { fg = "subtext", bg = "surface0" }
"ui.bufferline.active" = { fg = "violet", bg = "surface1", underline = { color = "violet", style = "line" } }
"ui.bufferline.background" = { bg = "surface0" }

"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "surface1", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "dimmed" }
"ui.text.directory" = { fg = "text" }

"ui.virtual" = "overlay0"
"ui.virtual.ruler" = { bg = "surface1" }
"ui.virtual.indent-guide" = "surface1"
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "surface0" }
"ui.virtual.jump-label" = { fg = "pink", modifiers = ["bold"] }

"ui.selection" = { bg = "surface1" }

"ui.cursor" = { fg = "background", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "background", bg = "violet" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "background", bg = "violet" }
"ui.cursor.primary.insert" = { fg = "background", bg = "green" }
"ui.cursor.primary.select" = { fg = "background", bg = "blue" }

"ui.cursor.normal" = { fg = "background", bg = "secondary_cursor_normal" }
"ui.cursor.insert" = { fg = "background", bg = "secondary_cursor_insert" }
"ui.cursor.select" = { fg = "background", bg = "secondary_cursor_select" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"ui.menu" = { fg = "text", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

error = "red"
warning = "yellow"
info = "blue"
hint = "teal"

rainbow = ["red", "orange", "yellow", "green", "teal", "blue", "violet"]

[palette]
pink = "#C394C2"
violet = "#A19DD4"
red = "#DF8BA0"
orange = "#C79A76"
yellow = "#C7B96F"
green = "#75B087"
teal = "#5EB1AF"
blue = "#7AA8CE"
text = "#A2A2A9"
subtext = "#878794"
overlay2 = "#7D7D7D"
overlay1 = "#808084"
overlay0 = "#84848C"
dimmed = "#7C7992"
surface1 = "#353144"
background = "#191724"
surface0 = "#08090C"

cursorline = "#08090C"
secondary_cursor = "#C394C2"
secondary_cursor_select = "#7AA8CE"
secondary_cursor_normal = "#C394C2"
secondary_cursor_insert = "#75B087"
