color=faf4ed
bs-hl-color=6f58a2
caps-lock-bs-hl-color=6f58a2
caps-lock-key-hl-color=247500
inside-color=faf4ed
inside-clear-color=faf4ed
inside-caps-lock-color=faf4ed
inside-ver-color=faf4ed
inside-wrong-color=faf4ed
key-hl-color=247500
layout-bg-color=#00000000
layout-border-color=#00000000
layout-text-color=6b635c
line-color=#00000000
line-clear-color=#00000000
line-caps-lock-color=#00000000
line-ver-color=#00000000
line-wrong-color=#00000000
ring-color=efe3d7
ring-clear-color=6f58a2
ring-caps-lock-color=9a5518
ring-ver-color=2169a6
ring-wrong-color=b43b3e
separator-color=#00000000
text-color=6b635c
text-clear-color=6f58a2
text-caps-lock-color=9a5518
text-ver-color=2169a6
text-wrong-color=b43b3e
