color=191724
bs-hl-color=a19dd4
caps-lock-bs-hl-color=a19dd4
caps-lock-key-hl-color=75b087
inside-color=191724
inside-clear-color=191724
inside-caps-lock-color=191724
inside-ver-color=191724
inside-wrong-color=191724
key-hl-color=75b087
layout-bg-color=#00000000
layout-border-color=#00000000
layout-text-color=a2a2a9
line-color=#00000000
line-clear-color=#00000000
line-caps-lock-color=#00000000
line-ver-color=#00000000
line-wrong-color=#00000000
ring-color=2a292d
ring-clear-color=a19dd4
ring-caps-lock-color=c79a76
ring-ver-color=7aa8ce
ring-wrong-color=df8ba0
separator-color=#00000000
text-color=a2a2a9
text-clear-color=a19dd4
text-caps-lock-color=c79a76
text-ver-color=7aa8ce
text-wrong-color=df8ba0
