# vim:set ft=tmux:

# --> {{name}}

# Main
set -ogq @thm_background "{{background}}"
set -ogq @thm_text "{{text}}"

# Colors
set -ogq @thm_violet "{{violet}}"
set -ogq @thm_pink "{{pink}}"
set -ogq @thm_red "{{red}}"
set -ogq @thm_yellow "{{yellow}}"
set -ogq @thm_orange "{{orange}}"
set -ogq @thm_green "{{green}}"
set -ogq @thm_teal "{{teal}}"
set -ogq @thm_blue "{{blue}}"

# Surfaces and overlays
set -ogq @thm_subtext "{{subtext}}"
set -ogq @thm_overlay_2 "{{overlay2}}"
set -ogq @thm_overlay_1 "{{overlay1}}"
set -ogq @thm_overlay_0 "{{overlay0}}"
set -ogq @thm_dimmed "{{dimmed}}"
set -ogq @thm_surface_1 "{{surface1}}"
set -ogq @thm_surface_0 "{{surface0}}"
