# vim:set ft=tmux:

# --> Blueberry Peach (Light)
set -ogq @thm_bg "{{background}}"
set -ogq @thm_fg "{{text}}"

# Colors
set -ogq @thm_mauve "{{violet}}"
set -ogq @thm_pink "{{violet}}"
set -ogq @thm_flamingo "{{pink}}"
set -ogq @thm_rosewater "{{pink}}"
set -ogq @thm_red "{{red}}"
set -ogq @thm_maroon "{{red}}"
set -ogq @thm_yellow "{{yellow}}"
set -ogq @thm_peach "{{orange}}"
set -ogq @thm_green "{{green}}"
set -ogq @thm_teal "{{teal}}"
set -ogq @thm_sky "{{teal}}"
set -ogq @thm_sapphire "{{teal}}"
set -ogq @thm_blue "{{blue}}"
set -ogq @thm_lavender "{{blue}}"

# Surfaces and overlays
set -ogq @thm_subtext_1 "{{subtext}}"
set -ogq @thm_subtext_0 "{{subtext}}"
set -ogq @thm_overlay_2 "{{overlay2}}"
set -ogq @thm_overlay_1 "{{overlay1}}"
set -ogq @thm_overlay_0 "{{overlay0}}"
set -ogq @thm_surface_2 "{{dimmed}}"
set -ogq @thm_surface_1 "{{surface1}}"
set -ogq @thm_surface_0 "{{surface1}}"
set -ogq @thm_mantle "{{surface0}}"
set -ogq @thm_crust "{{surface0}}"

set -g @catppuccin_window_text " #W #F"
set -g @catppuccin_window_current_text " #W #F"
