[colors]
ansi = [
  '#F3E2D3',
  '#B43B3E',
  '#247500',
  '#807000',
  '#2169A6',
  '#6F58A2',
  '#017468',
  '#746E68',
]
background = '#FAF4ED'
brights = [
  '#8B6E6E',
  '#B43B3E',
  '#247500',
  '#807000',
  '#2169A6',
  '#6F58A2',
  '#017468',
  '#746E68',
]
compose_cursor = '#A5407B'
cursor_bg = '#6F58A2'
cursor_border = '#6F58A2'
cursor_fg = '#FEFDFB'
foreground = '#6B635C'
scrollbar_thumb = '#8B6E6E'
selection_bg = '#F3E2D3'
selection_fg = '#6B635C'
split = '#8F8982'
visual_bell = '#F3E2D3'

[colors.indexed]
16 = '#9A5518'
17 = '#A5407B'

[colors.tab_bar]
background = '#FEFDFB'
inactive_tab_edge = '#F3E2D3'

[colors.tab_bar.active_tab]
bg_color = '#6F58A2'
fg_color = '#FEFDFB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#FEFDFB'
fg_color = '#6B635C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#FAF4ED'
fg_color = '#6B635C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F3E2D3'
fg_color = '#6B635C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#F3E2D3'
fg_color = '#6B635C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Light'
