[colors]
ansi = [
  '#EFE3D7',
  '#B22F32',
  '#186F11',
  '#7a6e00',
  '#226491',
  '#62569A',
  '#096C62',
  '#76706A',
]
background = '#FAF4ED'
brights = [
  '#8B6E6E',
  '#B22F32',
  '#186F11',
  '#7a6e00',
  '#226491',
  '#62569A',
  '#096C62',
  '#76706A',
]
compose_cursor = '#8E4876'
cursor_bg = '#62569A'
cursor_border = '#62569A'
cursor_fg = '#FEFDFB'
foreground = '#68625A'
scrollbar_thumb = '#8B6E6E'
selection_bg = '#EFE3D7'
selection_fg = '#68625A'
split = '#8F8982'
visual_bell = '#EFE3D7'

[colors.indexed]
16 = '#954D04'
17 = '#8E4876'

[colors.tab_bar]
background = '#FEFDFB'
inactive_tab_edge = '#EFE3D7'

[colors.tab_bar.active_tab]
bg_color = '#62569A'
fg_color = '#FEFDFB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#FEFDFB'
fg_color = '#68625A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#FAF4ED'
fg_color = '#68625A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#EFE3D7'
fg_color = '#68625A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#EFE3D7'
fg_color = '#68625A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Light'
