[colors]
ansi = [
  '#353144',
  '#DF8BA0',
  '#75B087',
  '#B4A25A',
  '#7AA8CE',
  '#A69CD9',
  '#5EB1AF',
  '#8D8DA5',
]
background = '#191724'
brights = [
  '#838098',
  '#DF8BA0',
  '#75B087',
  '#B4A25A',
  '#7AA8CE',
  '#A69CD9',
  '#5EB1AF',
  '#8D8DA5',
]
compose_cursor = '#C394C2'
cursor_bg = '#A69CD9'
cursor_border = '#A69CD9'
cursor_fg = '#08090C'
foreground = '#A0A1B6'
scrollbar_thumb = '#838098'
selection_bg = '#353144'
selection_fg = '#A0A1B6'
split = '#838098'
visual_bell = '#353144'

[colors.indexed]
16 = '#C79A76'
17 = '#C394C2'

[colors.tab_bar]
background = '#08090C'
inactive_tab_edge = '#353144'

[colors.tab_bar.active_tab]
bg_color = '#A69CD9'
fg_color = '#08090C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#08090C'
fg_color = '#A0A1B6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#191724'
fg_color = '#A0A1B6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#353144'
fg_color = '#A0A1B6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#353144'
fg_color = '#A0A1B6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Dark'
