[colors]
ansi = [
  '#37363E',
  '#F18385',
  '#50B850',
  '#A6A900',
  '#56A7FF',
  '#A097FF',
  '#0CB6B4',
  '#878794',
]
background = '#191724'
brights = [
  '#7C7992',
  '#F18385',
  '#50B850',
  '#A6A900',
  '#56A7FF',
  '#A097FF',
  '#0CB6B4',
  '#878794',
]
compose_cursor = '#DF81DD'
cursor_bg = '#A097FF'
cursor_border = '#A097FF'
cursor_fg = '#0B0A0F'
foreground = '#A2A2A9'
scrollbar_thumb = '#7C7992'
selection_bg = '#37363E'
selection_fg = '#A2A2A9'
split = '#84848C'
visual_bell = '#37363E'

[colors.indexed]
16 = '#E98D49'
17 = '#DF81DD'

[colors.tab_bar]
background = '#0B0A0F'
inactive_tab_edge = '#37363E'

[colors.tab_bar.active_tab]
bg_color = '#A097FF'
fg_color = '#0B0A0F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0B0A0F'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#191724'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#37363E'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#37363E'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Dark'
