[colors]
ansi = [
  '#2A292D',
  '#DF8BA0',
  '#75B087',
  '#C7B96F',
  '#7AA8CE',
  '#A19DD4',
  '#5EB1AF',
  '#878794',
]
background = '#191724'
brights = [
  '#7C7992',
  '#DF8BA0',
  '#75B087',
  '#C7B96F',
  '#7AA8CE',
  '#A19DD4',
  '#5EB1AF',
  '#878794',
]
compose_cursor = '#C394C2'
cursor_bg = '#A19DD4'
cursor_border = '#A19DD4'
cursor_fg = '#08090C'
foreground = '#A2A2A9'
scrollbar_thumb = '#7C7992'
selection_bg = '#2A292D'
selection_fg = '#A2A2A9'
split = '#84848C'
visual_bell = '#2A292D'

[colors.indexed]
16 = '#C79A76'
17 = '#C394C2'

[colors.tab_bar]
background = '#08090C'
inactive_tab_edge = '#2A292D'

[colors.tab_bar.active_tab]
bg_color = '#A19DD4'
fg_color = '#08090C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#08090C'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#191724'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2A292D'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2A292D'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Dark'
