[colors]
ansi = [
  '#FEFDFB',
  '#B43B3E',
  '#247500',
  '#8A5C05',
  '#2169A6',
  '#6F58A2',
  '#03726A',
  '#866864',
]
background = '#FAF4ED'
brights = [
  '#F3E2D3',
  '#B43B3E',
  '#247500',
  '#8A5C05',
  '#2169A6',
  '#A5407B',
  '#03726A',
  '#6C6460',
]
compose_cursor = '#A5407B'
cursor_bg = '#6F58A2'
cursor_border = '#6F58A2'
cursor_fg = '#FEFDFB'
foreground = '#6C6460'
scrollbar_thumb = '#8B6E6E'
selection_bg = '#F3E2D3'
selection_fg = '#6C6460'
split = '#8B6E6E'
visual_bell = '#F3E2D3'

[colors.indexed]
16 = '#A7491B'
17 = '#A5407B'

[colors.tab_bar]
background = '#FEFDFB'
inactive_tab_edge = '#F3E2D3'

[colors.tab_bar.active_tab]
bg_color = '#6F58A2'
fg_color = '#FEFDFB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#FEFDFB'
fg_color = '#6C6460'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#FAF4ED'
fg_color = '#6C6460'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F3E2D3'
fg_color = '#6C6460'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#F3E2D3'
fg_color = '#6C6460'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Light'
