[colors]
ansi = [
  '#2D2B37',
  '#DF8BA0',
  '#75B087',
  '#B7A338',
  '#72AAC9',
  '#A19DD4',
  '#5EB1AF',
  '#878794',
]
background = '#191724'
brights = [
  '#7C7992',
  '#DF8BA0',
  '#75B087',
  '#B7A338',
  '#72AAC9',
  '#A19DD4',
  '#5EB1AF',
  '#878794',
]
compose_cursor = '#C394C0'
cursor_bg = '#A19DD4'
cursor_border = '#A19DD4'
cursor_fg = '#0B0A0F'
foreground = '#A2A2A9'
scrollbar_thumb = '#7C7992'
selection_bg = '#2D2B37'
selection_fg = '#A2A2A9'
split = '#84848C'
visual_bell = '#2D2B37'

[colors.indexed]
16 = '#C79A76'
17 = '#C394C0'

[colors.tab_bar]
background = '#0B0A0F'
inactive_tab_edge = '#2D2B37'

[colors.tab_bar.active_tab]
bg_color = '#A19DD4'
fg_color = '#0B0A0F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0B0A0F'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#191724'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2D2B37'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2D2B37'
fg_color = '#A2A2A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'schemar'
name = 'Blueberry Peach Dark'
