return {
  red = "red",
  yellow = "yellow",
  orange = "peach",
  green = "green",
  teal = "teal",
  blue = "blue",
  violet = "mauve",
  pink = "flamingo",
  text = "text",
  subtext = "subtext1",
  overlay2 = "overlay2",
  overlay1 = "overlay1",
  overlay0 = "overlay0",
  dimmed = "surface2",
  surface1 = "surface0",
  background = "base",
  surface0 = "mantle",
}
