return {
  red = "red",
  maroon = "red",
  yellow = "yellow",
  peach = "orange",
  green = "green",
  teal = "teal",
  sky = "teal",
  sapphire = "teal",
  blue = "blue",
  lavender = "blue",
  mauve = "violet",
  pink = "violet",
  flamingo = "pink",
  rosewater = "pink",
  text = "text",
  subtext1 = "subtext",
  subtext0 = "subtext",
  overlay2 = "overlay2",
  overlay1 = "overlay1",
  overlay0 = "overlay0",
  surface2 = "dimmed",
  surface1 = "surface1",
  surface0 = "surface1",
  base = "background",
  mantle = "surface0",
  crust = "surface0",
}
