# vim:ft=kitty

## name: Blueberry Peach Dark
## author: schemar
## license: MIT
## upstream: https://github.com/schemar/blueberry-peach/blob/main/ports/kitty/blueberry_peach_dark.conf
## blurb: Handcrafted dark *and* light color scheme with a focus on legibility
## and consistency

#: The basic colors

foreground                      #9FA2BC
background                      #191724
selection_foreground            #9FA2BC
selection_background            #353144


#: Cursor colors

cursor                          #A69CD9
cursor_text_color               #191724
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #7AA8CE


#: kitty window border colors and terminal bell colors

active_border_color             #A69CD9
inactive_border_color           #838098
bell_border_color               #DF8BA0
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #191724
macos_titlebar_color            #191724


#: Tab bar colors

active_tab_foreground           #9FA2BC
active_tab_background           #353144
inactive_tab_foreground         #838098
inactive_tab_background         #191724
tab_bar_background              #08090C
tab_bar_margin_color            #838098


#: Colors for marks (marked text in the terminal)

mark1_foreground #191724
mark1_background #5EB1AF
mark2_foreground #191724
mark2_background #C79A76
mark3_foreground #191724
mark3_background #C394C2


#: The basic 16 colors

#: black
color0 #08090C
color8 #353144

#: red
color1 #DF8BA0
color9 #DF8BA0

#: green
color2  #75B087
color10 #75B087

#: yellow
color3  #B6A358
color11 #B6A358

#: blue
color4  #7AA8CE
color12 #7AA8CE

#: magenta
color5  #A69CD9
color13 #C394C2

#: cyan
color6  #5EB1AF
color14 #5EB1AF

#: white
color7  #8D8DA5
color15 #9FA2BC


#: You can set the remaining 240 colors as color16 to color255.
