# vim:ft=kitty

## name: Blueberry Peach Light
## author: schemar
## license: MIT
## upstream: https://github.com/schemar/blueberry-peach/blob/main/ports/kitty/blueberry_peach_light.conf
## blurb: Handcrafted dark *and* light color scheme with a focus on legibility
## and consistency

#: The basic colors

foreground                      #6C6460
background                      #FAF4ED
selection_foreground            #6C6460
selection_background            #F3E2D3


#: Cursor colors

cursor                          #6F58A2
cursor_text_color               #FAF4ED
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #2169A6


#: kitty window border colors and terminal bell colors

active_border_color             #6F58A2
inactive_border_color           #8B6E6E
bell_border_color               #B43B3E
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #FAF4ED
macos_titlebar_color            #FAF4ED


#: Tab bar colors

active_tab_foreground           #6C6460
active_tab_background           #F3E2D3
inactive_tab_foreground         #8B6E6E
inactive_tab_background         #FAF4ED
tab_bar_background              #FEFDFB
tab_bar_margin_color            #8B6E6E


#: Colors for marks (marked text in the terminal)

mark1_foreground #FAF4ED
mark1_background #03726A
mark2_foreground #FAF4ED
mark2_background #A7491B
mark3_foreground #FAF4ED
mark3_background #A5407B


#: The basic 16 colors

#: black
color0 #FEFDFB
color8 #F3E2D3

#: red
color1 #B43B3E
color9 #B43B3E

#: green
color2  #247500
color10 #247500

#: yellow
color3  #8A5C05
color11 #8A5C05

#: blue
color4  #2169A6
color12 #2169A6

#: magenta
color5  #6F58A2
color13 #A5407B

#: cyan
color6  #03726A
color14 #03726A

#: white
color7  #866864
color15 #6C6460


#: You can set the remaining 240 colors as color16 to color255.
