# vim:set ft=tmux:

# --> Blueberry Peach (Light)
set -ogq @thm_bg "#FAF4ED"
set -ogq @thm_fg "#706F7A"

# Colors
set -ogq @thm_mauve "#725ED5"
set -ogq @thm_pink "#725ED5"
set -ogq @thm_flamingo "#AB4AA9"
set -ogq @thm_rosewater "#AB4AA9"
set -ogq @thm_red "#D52067"
set -ogq @thm_maroon "#D52067"
set -ogq @thm_yellow "#8A6B00"
set -ogq @thm_peach "#C33513"
set -ogq @thm_green "#1D8200"
set -ogq @thm_teal "#007D85"
set -ogq @thm_sky "#007D85"
set -ogq @thm_sapphire "#007D85"
set -ogq @thm_blue "#0074C2"
set -ogq @thm_lavender "#0074C2"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#757480"
set -ogq @thm_subtext_0 "#757480"
set -ogq @thm_overlay_2 "#857F79"
set -ogq @thm_overlay_1 "#8A847D"
set -ogq @thm_overlay_0 "#8F8982"
set -ogq @thm_surface_2 "#9C8282"
set -ogq @thm_surface_1 "#EBDFD3"
set -ogq @thm_surface_0 "#EBDFD3"
set -ogq @thm_mantle "#FCF9F5"
set -ogq @thm_crust "#FCF9F5"

set -g @catppuccin_window_text " #W #F"
set -g @catppuccin_window_current_text " #W #F"
