# vim:set ft=tmux:

# --> Blueberry Peach Dark

# Main
set -ogq @thm_background "#191724"
set -ogq @thm_text "#A0A1B6"

# Colors
set -ogq @thm_violet "#A69CD9"
set -ogq @thm_pink "#C394C2"
set -ogq @thm_red "#DF8BA0"
set -ogq @thm_yellow "#C7B96F"
set -ogq @thm_orange "#C79A76"
set -ogq @thm_green "#75B087"
set -ogq @thm_teal "#5EB1AF"
set -ogq @thm_blue "#7AA8CE"

# Surfaces
set -ogq @thm_subtext "#8D8DA5"
set -ogq @thm_dimmed "#838098"
set -ogq @thm_surface_1 "#353144"
set -ogq @thm_surface_0 "#08090C"
