# vim:set ft=tmux:

# --> Blueberry Peach (Light)
set -ogq @thm_bg "#191724"
set -ogq @thm_fg "#A2A2A9"

# Colors
set -ogq @thm_mauve "#A097FF"
set -ogq @thm_pink "#A097FF"
set -ogq @thm_flamingo "#DF81DD"
set -ogq @thm_rosewater "#DF81DD"
set -ogq @thm_red "#F18385"
set -ogq @thm_maroon "#F18385"
set -ogq @thm_yellow "#A6A900"
set -ogq @thm_peach "#E98D49"
set -ogq @thm_green "#50B850"
set -ogq @thm_teal "#0CB6B4"
set -ogq @thm_sky "#0CB6B4"
set -ogq @thm_sapphire "#0CB6B4"
set -ogq @thm_blue "#56A7FF"
set -ogq @thm_lavender "#56A7FF"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#878794"
set -ogq @thm_subtext_0 "#878794"
set -ogq @thm_overlay_2 "#7D7D7D"
set -ogq @thm_overlay_1 "#808084"
set -ogq @thm_overlay_0 "#84848C"
set -ogq @thm_surface_2 "#7C7992"
set -ogq @thm_surface_1 "#37363E"
set -ogq @thm_surface_0 "#37363E"
set -ogq @thm_mantle "#0B0A0F"
set -ogq @thm_crust "#0B0A0F"

set -g @catppuccin_window_text " #W #F"
set -g @catppuccin_window_current_text " #W #F"
