# vim:set ft=tmux:

# --> Blueberry Peach (Light)
set -ogq @thm_bg "#FAF4ED"
set -ogq @thm_fg "#57534C"

# Colors
set -ogq @thm_mauve "#6E3B96"
set -ogq @thm_pink "#6E3B96"
set -ogq @thm_flamingo "#8F2E68"
set -ogq @thm_rosewater "#8F2E68"
set -ogq @thm_red "#9D2033"
set -ogq @thm_maroon "#9D2033"
set -ogq @thm_yellow "#7C5C00"
set -ogq @thm_peach "#8A3B00"
set -ogq @thm_green "#0C610C"
set -ogq @thm_teal "#245C53"
set -ogq @thm_sky "#245C53"
set -ogq @thm_sapphire "#245C53"
set -ogq @thm_blue "#374D9F"
set -ogq @thm_lavender "#374D9F"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#6E6863"
set -ogq @thm_subtext_0 "#6E6863"
set -ogq @thm_overlay_2 "#857F79"
set -ogq @thm_overlay_1 "#8A847D"
set -ogq @thm_overlay_0 "#8F8982"
set -ogq @thm_surface_2 "#8B6E6E"
set -ogq @thm_surface_1 "#DDC8B6"
set -ogq @thm_surface_0 "#DDC8B6"
set -ogq @thm_mantle "#FEFCFB"
set -ogq @thm_crust "#FEFCFB"

set -g @catppuccin_window_text " #W #F"
set -g @catppuccin_window_current_text " #W #F"
