# vim:set ft=tmux:

# --> Blueberry Peach Light

# Main
set -ogq @thm_background "#FAF4ED"
set -ogq @thm_text "#6B635C"

# Colors
set -ogq @thm_violet "#6F58A2"
set -ogq @thm_pink "#A5407B"
set -ogq @thm_red "#B43B3E"
set -ogq @thm_yellow "#8A5C05"
set -ogq @thm_orange "#A7491B"
set -ogq @thm_green "#247500"
set -ogq @thm_teal "#017468"
set -ogq @thm_blue "#2169A6"

# Surfaces
set -ogq @thm_subtext "#6D675F"
set -ogq @thm_dimmed "#8B6E6E"
set -ogq @thm_surface_1 "#F3E2D3"
set -ogq @thm_surface_0 "#FEFDFB"
