# vim:set ft=tmux:

# --> Blueberry Peach Dark

# Main
set -ogq @thm_background "#191724"
set -ogq @thm_text "#A2A2A9"

# Colors
set -ogq @thm_violet "#A19DD4"
set -ogq @thm_pink "#C394C2"
set -ogq @thm_red "#DF8BA0"
set -ogq @thm_yellow "#C7B96F"
set -ogq @thm_orange "#C79A76"
set -ogq @thm_green "#75B087"
set -ogq @thm_teal "#5EB1AF"
set -ogq @thm_blue "#7AA8CE"

# Surfaces and overlays
set -ogq @thm_subtext "#878794"
set -ogq @thm_overlay_2 "#7D7D7D"
set -ogq @thm_overlay_1 "#808084"
set -ogq @thm_overlay_0 "#84848C"
set -ogq @thm_dimmed "#7C7992"
set -ogq @thm_surface_1 "#353144"
set -ogq @thm_surface_0 "#08090C"
